# Basic transformations practice

# This code has been generated by ChatGPT
import numpy as np
import matplotlib.pyplot as plt
import  python_journey.helper_modules.plot_helper as ph

A = np.array([[1, 2],
              [3, 1]])  # Example matrix

v = np.array([[1, 0], [0, 1]])  # Basis vectors

fig, (ax1, ax2) = plt.subplots(1,2)
ph.plot_2d_vector_from_matrix(ax1, A, "green")
ph.plot_2d_vector_from_matrix(ax2, A.T, "green")
ax1.set_title("Original Matrix")
ax1.set_aspect('equal')
ax1.set_xlim(-5,5)
ax1.set_ylim(-5,5)
ax1.grid()
ax2.set_title("Transposed Matrix")
ax2.set_aspect('equal')
ax2.set_xlim(-5,5)
ax2.set_ylim(-5,5)
ax2.grid()
plt.suptitle("Matrix transformations")
plt.show()


